// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using RestaurantQrAiOrdering.Api.Data;

#nullable disable

namespace RestaurantQrAiOrdering.Api.Data.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    [Migration("20260613135200_AddTableSessions")]
    partial class AddTableSessions
    {
    }
}
