// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RestaurantQrAiOrdering.Api.Data;

#nullable disable

namespace RestaurantQrAiOrdering.Api.Data.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    partial class RestaurantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RestaurantQrAiOrdering.Entities.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("IsActive");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "cat_appetizer",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(1865), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 10,
                            IsActive = true,
                            Name = "Khai vi",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(1865), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "cat_main",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(1865), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 20,
                            IsActive = true,
                            Name = "Mon chinh",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(1865), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "cat_noodle",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(1865), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 30,
                            IsActive = true,
                            Name = "Pho va bun",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(1865), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "cat_seafood",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(1865), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 40,
                            IsActive = true,
                            Name = "Hai san",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(1865), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "cat_drink",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(1865), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 50,
                            IsActive = true,
                            Name = "Do uong",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(1865), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "cat_dessert",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(1865), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 60,
                            IsActive = true,
                            Name = "Trang mieng",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(1865), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("RestaurantQrAiOrdering.Entities.ChatMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("ChatSessionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("chat_session_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("SuggestedCartActionsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("suggested_cart_actions_json");

                    b.HasKey("Id");

                    b.HasIndex("ChatSessionId");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("RestaurantQrAiOrdering.Entities.ChatSession", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_closed");

                    b.Property<string>("OrderId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_id");

                    b.Property<string>("RestaurantTableId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("restaurant_table_id");

                    b.Property<string>("TableCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("table_code");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsClosed");

                    b.HasIndex("OrderId");

                    b.HasIndex("RestaurantTableId");

                    b.ToTable("chat_sessions", (string)null);
                });

            modelBuilder.Entity("RestaurantQrAiOrdering.Entities.KnowledgeEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Embedding")
                        .HasColumnType("jsonb")
                        .HasColumnName("embedding");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("MenuItemId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("menu_item_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_type");

                    b.Property<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("MenuItemId");

                    b.ToTable("knowledge_entries", (string)null);
                });

            modelBuilder.Entity("RestaurantQrAiOrdering.Entities.MenuItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("IsAvailable");

                    b.ToTable("menu_items", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "m_001",
                            CategoryId = "cat_main",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(3524), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Ga chien gion, com thom, dua chua.",
                            ImageUrl = "https://example.com/images/com-ga-xoi-mo.jpg",
                            IsAvailable = true,
                            Name = "Com ga xoi mo",
                            Price = 45000m,
                            Tags = new[] { "pho bien", "mon chinh", "signature" },
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(3524), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "m_002",
                            CategoryId = "cat_main",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(3524), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Suon uop mat ong nuong than, an kem rau chua.",
                            ImageUrl = "https://example.com/images/com-suon-nuong.jpg",
                            IsAvailable = true,
                            Name = "Com suon nuong",
                            Price = 52000m,
                            Tags = new[] { "pho bien", "nuong" },
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(3524), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "m_003",
                            CategoryId = "cat_noodle",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(3524), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Pho bo nuoc dung trong, bo tai mem, rau thom.",
                            ImageUrl = "https://example.com/images/pho-bo-tai.jpg",
                            IsAvailable = true,
                            Name = "Pho bo tai",
                            Price = 55000m,
                            Tags = new[] { "nong", "pho", "bo" },
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(3524), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "m_004",
                            CategoryId = "cat_noodle",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(3524), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Nuoc dung dam vi sa te, bo, cha cua va rau song.",
                            ImageUrl = "https://example.com/images/bun-bo-hue.jpg",
                            IsAvailable = false,
                            Name = "Bun bo Hue",
                            Price = 60000m,
                            Tags = new[] { "cay", "het hang", "unavailable-demo" },
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(3524), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "m_005",
                            CategoryId = "cat_appetizer",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(3524), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Goi cuon tuoi kem nuoc cham dau phong.",
                            ImageUrl = "https://example.com/images/goi-cuon.jpg",
                            IsAvailable = true,
                            Name = "Goi cuon tom thit",
                            Price = 39000m,
                            Tags = new[] { "fresh", "light" },
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(3524), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "m_006",
                            CategoryId = "cat_appetizer",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(3524), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Cha gio gion nhan hai san, sot mayo cay.",
                            ImageUrl = "https://example.com/images/cha-gio-hai-san.jpg",
                            IsAvailable = true,
                            Name = "Cha gio hai san",
                            Price = 42000m,
                            Tags = new[] { "chien gion", "seafood" },
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(3524), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "m_007",
                            CategoryId = "cat_seafood",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(3524), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Tom tuoi rang muoi ot, an kem rau thom.",
                            ImageUrl = "https://example.com/images/tom-rang-muoi.jpg",
                            IsAvailable = true,
                            Name = "Tom rang muoi",
                            Price = 185000m,
                            Tags = new[] { "seafood", "share" },
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(3524), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "m_008",
                            CategoryId = "cat_seafood",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(3524), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Lau Thai chua cay voi tom, muc, ca va rau tuoi.",
                            ImageUrl = "https://example.com/images/lau-thai-hai-san.jpg",
                            IsAvailable = true,
                            Name = "Lau Thai hai san",
                            Price = 345000m,
                            Tags = new[] { "spicy", "seafood", "share" },
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(3524), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "m_009",
                            CategoryId = "cat_drink",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(3524), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Tra dao mat lanh voi cam vang va sa tuoi.",
                            ImageUrl = "https://example.com/images/tra-dao-cam-sa.jpg",
                            IsAvailable = true,
                            Name = "Tra dao cam sa",
                            Price = 55000m,
                            Tags = new[] { "drink", "fresh" },
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(3524), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "m_010",
                            CategoryId = "cat_drink",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(3524), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Ca phe rang xay pha phin, sua dac va da vien.",
                            ImageUrl = "https://example.com/images/ca-phe-sua-da.jpg",
                            IsAvailable = false,
                            Name = "Ca phe sua da",
                            Price = 45000m,
                            Tags = new[] { "drink", "coffee", "unavailable-demo" },
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(3524), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "m_011",
                            CategoryId = "cat_dessert",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(3524), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Khuc bach beo nhe, vai, hanh nhan va siro duong phen.",
                            ImageUrl = "https://example.com/images/che-khuc-bach.jpg",
                            IsAvailable = true,
                            Name = "Che khuc bach",
                            Price = 55000m,
                            Tags = new[] { "sweet", "cool" },
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(3524), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "m_012",
                            CategoryId = "cat_dessert",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(3524), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Banh flan min, caramel thom, dung lanh.",
                            ImageUrl = "https://example.com/images/banh-flan.jpg",
                            IsAvailable = true,
                            Name = "Banh flan caramel",
                            Price = 35000m,
                            Tags = new[] { "sweet", "classic" },
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(3524), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("RestaurantQrAiOrdering.Entities.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeliveryAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("delivery_address");

                    b.Property<string>("DeliveryNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("delivery_note");

                    b.Property<string>("DeliveryPhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("delivery_phone_number");

                    b.Property<string>("DeliveryRecipientName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("delivery_recipient_name");

                    b.Property<decimal>("MockDeliveryFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("mock_delivery_fee");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_code");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("order_type");

                    b.Property<string>("PickupCustomerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("pickup_customer_name");

                    b.Property<string>("PickupCustomerPhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("pickup_customer_phone");

                    b.Property<DateTimeOffset?>("PickupRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pickup_requested_at");

                    b.Property<string>("RestaurantTableId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("restaurant_table_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("SubtotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("subtotal_amount");

                    b.Property<string>("TableCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("table_code");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("OrderCode")
                        .IsUnique();

                    b.HasIndex("RestaurantTableId");

                    b.HasIndex("Status");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("RestaurantQrAiOrdering.Entities.OrderItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MenuItemId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("menu_item_id");

                    b.Property<string>("MenuItemName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("menu_item_name");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("RestaurantQrAiOrdering.Entities.Payment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("method");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_id");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("ProviderTransactionId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_transaction_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("RestaurantQrAiOrdering.Entities.RestaurantTable", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("QrToken")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("qr_token");

                    b.Property<string>("TableCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("table_code");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("QrToken")
                        .IsUnique();

                    b.HasIndex("TableCode")
                        .IsUnique();

                    b.ToTable("restaurant_tables", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "tbl_01",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(5563), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Ban 01",
                            IsActive = true,
                            QrToken = "qr-demo-t01",
                            TableCode = "T01",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(5563), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "tbl_02",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(5563), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Ban 02",
                            IsActive = true,
                            QrToken = "qr-demo-t02",
                            TableCode = "T02",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(5563), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "tbl_03",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(5563), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Ban 03",
                            IsActive = true,
                            QrToken = "qr-demo-t03",
                            TableCode = "T03",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(5563), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "tbl_04",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(5563), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Ban 04",
                            IsActive = true,
                            QrToken = "qr-demo-t04",
                            TableCode = "T04",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(5563), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "tbl_05",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(5563), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Ban 05",
                            IsActive = true,
                            QrToken = "qr-demo-t05",
                            TableCode = "T05",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(5563), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "tbl_06",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(5563), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Ban 06",
                            IsActive = true,
                            QrToken = "qr-demo-t06",
                            TableCode = "T06",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(5563), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "tbl_07",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(5563), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Ban 07",
                            IsActive = true,
                            QrToken = "qr-demo-t07",
                            TableCode = "T07",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(5563), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "tbl_08",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(5563), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Ban 08",
                            IsActive = true,
                            QrToken = "qr-demo-t08",
                            TableCode = "T08",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 3, 11, 23, 195, DateTimeKind.Unspecified).AddTicks(5563), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("RestaurantQrAiOrdering.Entities.ChatMessage", b =>
                {
                    b.HasOne("RestaurantQrAiOrdering.Entities.ChatSession", "ChatSession")
                        .WithMany("Messages")
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatSession");
                });

            modelBuilder.Entity("RestaurantQrAiOrdering.Entities.ChatSession", b =>
                {
                    b.HasOne("RestaurantQrAiOrdering.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RestaurantQrAiOrdering.Entities.RestaurantTable", "RestaurantTable")
                        .WithMany()
                        .HasForeignKey("RestaurantTableId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Order");

                    b.Navigation("RestaurantTable");
                });

            modelBuilder.Entity("RestaurantQrAiOrdering.Entities.KnowledgeEntry", b =>
                {
                    b.HasOne("RestaurantQrAiOrdering.Entities.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("RestaurantQrAiOrdering.Entities.MenuItem", b =>
                {
                    b.HasOne("RestaurantQrAiOrdering.Entities.Category", "Category")
                        .WithMany("MenuItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RestaurantQrAiOrdering.Entities.Order", b =>
                {
                    b.HasOne("RestaurantQrAiOrdering.Entities.RestaurantTable", "RestaurantTable")
                        .WithMany("Orders")
                        .HasForeignKey("RestaurantTableId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RestaurantTable");
                });

            modelBuilder.Entity("RestaurantQrAiOrdering.Entities.OrderItem", b =>
                {
                    b.HasOne("RestaurantQrAiOrdering.Entities.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("RestaurantQrAiOrdering.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RestaurantQrAiOrdering.Entities.Payment", b =>
                {
                    b.HasOne("RestaurantQrAiOrdering.Entities.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("RestaurantQrAiOrdering.Entities.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RestaurantQrAiOrdering.Entities.Category", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("RestaurantQrAiOrdering.Entities.ChatSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("RestaurantQrAiOrdering.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("RestaurantQrAiOrdering.Entities.RestaurantTable", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
